version: '3.4'
networks:
  hints:
    external: false
    ipam:
      config:
        - subnet: ${HINTS_SUBNET}
services:
  postgresql:
    restart: unless-stopped
    image: postgres:14.2
    shm_size: '2gb'
    ports:
      - "5432:5432"
    networks:
      hints:
        ipv4_address: ${POSTGRES_IP}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data:rw
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
  hints:
    restart: unless-stopped
    build:
      context: .
      # dockerfile: ./docker/Dockerfile
    ports:
      - "${SUPERVISORD_PORT}:9001"
      - "${HTTP_PORT}:5000"
    networks:
      hints:
        ipv4_address: ${HINTS_IP}
    hostname: ${STORAGE_HOSTNAME}
    environment:
      - HINTS_DB_CONNSTRING=${HINTS_DB_CONNSTRING}
      - STORAGE_HOSTNAME=${STORAGE_HOSTNAME}
    volumes:
      - ./app:/home/hints/app:rw